// <auto-generated />
using System;
using BeerFerment.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeerFerment.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260628200433_CreateFermentationParameters")]
    partial class CreateFermentationParameters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeerFerment.Api.Models.Beer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("style");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_beers");

                    b.ToTable("beers", (string)null);
                });

            modelBuilder.Entity("BeerFerment.Api.Models.FermentationParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BeerId")
                        .HasColumnType("uuid")
                        .HasColumnName("beer_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("MaxExtract")
                        .HasColumnType("numeric")
                        .HasColumnName("max_extract");

                    b.Property<decimal>("MaxPh")
                        .HasColumnType("numeric")
                        .HasColumnName("max_ph");

                    b.Property<decimal>("MaxTemperature")
                        .HasColumnType("numeric")
                        .HasColumnName("max_temperature");

                    b.Property<decimal>("MinExtract")
                        .HasColumnType("numeric")
                        .HasColumnName("min_extract");

                    b.Property<decimal>("MinPh")
                        .HasColumnType("numeric")
                        .HasColumnName("min_ph");

                    b.Property<decimal>("MinTemperature")
                        .HasColumnType("numeric")
                        .HasColumnName("min_temperature");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_fermentation_parameters");

                    b.HasIndex("BeerId")
                        .IsUnique()
                        .HasDatabaseName("ix_fermentation_parameters_beer_id");

                    b.ToTable("fermentation_parameters", (string)null);
                });

            modelBuilder.Entity("BeerFerment.Api.Models.Tank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CapacityLiters")
                        .HasColumnType("numeric")
                        .HasColumnName("capacity_liters");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tanks");

                    b.ToTable("tanks", (string)null);
                });

            modelBuilder.Entity("BeerFerment.Api.Models.FermentationParameter", b =>
                {
                    b.HasOne("BeerFerment.Api.Models.Beer", "Beer")
                        .WithOne("FermentationParameter")
                        .HasForeignKey("BeerFerment.Api.Models.FermentationParameter", "BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fermentation_parameters_beers_beer_id");

                    b.Navigation("Beer");
                });

            modelBuilder.Entity("BeerFerment.Api.Models.Beer", b =>
                {
                    b.Navigation("FermentationParameter");
                });
#pragma warning restore 612, 618
        }
    }
}
