// <auto-generated />
using System;
using BrewMonitor.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BrewMonitor.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BrewMonitor.Api.Models.Beer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("style");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_beers");

                    b.ToTable("beers", (string)null);
                });

            modelBuilder.Entity("BrewMonitor.Api.Models.FermentationParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BeerId")
                        .HasColumnType("uuid")
                        .HasColumnName("beer_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("MaxExtract")
                        .HasColumnType("numeric")
                        .HasColumnName("max_extract");

                    b.Property<decimal>("MaxPh")
                        .HasColumnType("numeric")
                        .HasColumnName("max_ph");

                    b.Property<decimal>("MaxTemperature")
                        .HasColumnType("numeric")
                        .HasColumnName("max_temperature");

                    b.Property<decimal>("MinExtract")
                        .HasColumnType("numeric")
                        .HasColumnName("min_extract");

                    b.Property<decimal>("MinPh")
                        .HasColumnType("numeric")
                        .HasColumnName("min_ph");

                    b.Property<decimal>("MinTemperature")
                        .HasColumnType("numeric")
                        .HasColumnName("min_temperature");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_fermentation_parameters");

                    b.HasIndex("BeerId")
                        .IsUnique()
                        .HasDatabaseName("ix_fermentation_parameters_beer_id");

                    b.ToTable("fermentation_parameters", (string)null);
                });

            modelBuilder.Entity("BrewMonitor.Api.Models.FermentationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("batch_number");

                    b.Property<Guid>("BeerId")
                        .HasColumnType("uuid")
                        .HasColumnName("beer_id");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("classification");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Extract")
                        .HasColumnType("numeric")
                        .HasColumnName("extract");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("Ph")
                        .HasColumnType("numeric")
                        .HasColumnName("ph");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<Guid>("TankId")
                        .HasColumnType("uuid")
                        .HasColumnName("tank_id");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("numeric")
                        .HasColumnName("temperature");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_fermentation_records");

                    b.HasIndex("BatchNumber")
                        .HasDatabaseName("ix_fermentation_records_batch_number");

                    b.HasIndex("BeerId")
                        .HasDatabaseName("ix_fermentation_records_beer_id");

                    b.HasIndex("TankId")
                        .HasDatabaseName("ix_fermentation_records_tank_id");

                    b.ToTable("fermentation_records", (string)null);
                });

            modelBuilder.Entity("BrewMonitor.Api.Models.Tank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CapacityLiters")
                        .HasColumnType("numeric")
                        .HasColumnName("capacity_liters");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tanks");

                    b.ToTable("tanks", (string)null);
                });

            modelBuilder.Entity("BrewMonitor.Api.Models.FermentationParameter", b =>
                {
                    b.HasOne("BrewMonitor.Api.Models.Beer", "Beer")
                        .WithOne("FermentationParameter")
                        .HasForeignKey("BrewMonitor.Api.Models.FermentationParameter", "BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fermentation_parameters_beers_beer_id");

                    b.Navigation("Beer");
                });

            modelBuilder.Entity("BrewMonitor.Api.Models.FermentationRecord", b =>
                {
                    b.HasOne("BrewMonitor.Api.Models.Beer", "Beer")
                        .WithMany()
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fermentation_records_beers_beer_id");

                    b.HasOne("BrewMonitor.Api.Models.Tank", "Tank")
                        .WithMany()
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fermentation_records_tanks_tank_id");

                    b.Navigation("Beer");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("BrewMonitor.Api.Models.Beer", b =>
                {
                    b.Navigation("FermentationParameter");
                });
#pragma warning restore 612, 618
        }
    }
}
