@__HostAddress = http://localhost:5027

GET {{__HostAddress}}/api/beer
Accept: application/json

###

POST {{__HostAddress}}/api/beer
Content-Type: application/json

{
  "name": "American IPA",
  "style": "IPA"
}

###
